package com.weather.core.network.model.geosearch

import com.example.model.geocode.LocalNames
import kotlinx.serialization.Serializable

@Serializable
data class LocalNamesDto(
    val af: String? = null,
    val am: String? = null,
    val an: String? = null,
    val ar: String? = null,
    val ascii: String? = null,
    val az: String? = null,
    val ba: String? = null,
    val be: String? = null,
    val bg: String? = null,
    val bn: String? = null,
    val bo: String? = null,
    val br: String? = null,
    val bs: String? = null,
    val ca: String? = null,
    val cs: String? = null,
    val cv: String? = null,
    val cy: String? = null,
    val da: String? = null,
    val de: String? = null,
    val el: String? = null,
    val en: String? = null,
    val eo: String? = null,
    val es: String? = null,
    val et: String? = null,
    val eu: String? = null,
    val fa: String? = null,
    val feature_name: String? = null,
    val fi: String? = null,
    val fo: String? = null,
    val fr: String? = null,
    val fy: String? = null,
    val ga: String? = null,
    val gd: String? = null,
    val gl: String? = null,
    val he: String? = null,
    val hi: String? = null,
    val hr: String? = null,
    val ht: String? = null,
    val hu: String? = null,
    val hy: String? = null,
    val ia: String? = null,
    val id: String? = null,
    val ie: String? = null,
    val io: String? = null,
    val `is`: String? = null,
    val it: String? = null,
    val ja: String? = null,
    val ka: String? = null,
    val kk: String? = null,
    val kl: String? = null,
    val kn: String? = null,
    val ko: String? = null,
    val ku: String? = null,
    val kw: String? = null,
    val la: String? = null,
    val lb: String? = null,
    val lt: String? = null,
    val lv: String? = null,
    val mi: String? = null,
    val mk: String? = null,
    val ml: String? = null,
    val mn: String? = null,
    val mr: String? = null,
    val ms: String? = null,
    val my: String? = null,
    val nl: String? = null,
    val nn: String? = null,
    val no: String? = null,
    val oc: String? = null,
    val or: String? = null,
    val os: String? = null,
    val pa: String? = null,
    val pl: String? = null,
    val ps: String? = null,
    val pt: String? = null,
    val rm: String? = null,
    val ro: String? = null,
    val ru: String? = null,
    val sc: String? = null,
    val se: String? = null,
    val sk: String? = null,
    val sl: String? = null,
    val so: String? = null,
    val sq: String? = null,
    val sr: String? = null,
    val sv: String? = null,
    val sw: String? = null,
    val ta: String? = null,
    val te: String? = null,
    val tg: String? = null,
    val th: String? = null,
    val tk: String? = null,
    val tl: String? = null,
    val tr: String? = null,
    val tt: String? = null,
    val ug: String? = null,
    val uk: String? = null,
    val ur: String? = null,
    val uz: String? = null,
    val vi: String? = null,
    val vo: String? = null,
    val yi: String? = null,
    val yo: String? = null,
    val zh: String? = null
){
    fun toLocalNames(): LocalNames {
        return LocalNames(
            af,
            am,
            an,
            ar,
            ascii,
            az,
            ba,
            be,
            bg,
            bn,
            bo,
            br,
            bs,
            ca,
            cs,
            cv,
            cy,
            da,
            de,
            el,
            en,
            eo,
            es,
            et,
            eu,
            fa,
            feature_name,
            fi,
            fo,
            fr,
            fy,
            ga,
            gd,
            gl,
            he,
            hi,
            hr,
            ht,
            hu,
            hy,
            ia,
            id,
            ie,
            io,
            `is`,
            it,
            ja,
            ka,
            kk,
            kl,
            kn,
            ko,
            ku,
            kw,
            la,
            lb,
            lt,
            lv,
            mi,
            mk,
            ml,
            mn,
            mr,
            ms,
            my,
            nl,
            nn,
            no,
            oc,
            or,
            os,
            pa,
            pl,
            ps,
            pt,
            rm,
            ro,
            ru,
            sc,
            se,
            sk,
            sl,
            so,
            sq,
            sr,
            sv,
            sw,
            ta,
            te,
            tg,
            th,
            tk,
            tl,
            tr,
            tt,
            ug,
            uk,
            ur,
            uz,
            vi,
            vo,
            yi,
            yo,
            zh
        )
    }
}