package com.weather.feature.forecast.hourlydata

import com.weather.model.Hourly

internal val HourlyStaticData = listOf(
    Hourly(
        time = "13:00",
        sunriseSunset = "",
        humidity = 1,
        pressure = 0,
        temp = 8.0,
        uvi = 0.0,
        visibility = 100,
        winDirection = 10,
        windSpeed = 0.0,
        isDay = 0,
        iconUrl = "",
        weatherCode = 0
    ),
    Hourly(
        time = "14:00",
        sunriseSunset = "",
        humidity = 1,
        pressure = 0,
        temp = 9.0,
        uvi = 0.0,
        visibility = 100,
        winDirection = 10,
        windSpeed = 0.0,
        isDay = 0,
        iconUrl = "",
        weatherCode = 0
    ),
    Hourly(
        time = "15:00",
        sunriseSunset = "Sunrise",
        humidity = 1,
        pressure = 0,
        temp = 11.0,
        uvi = 0.0,
        visibility = 100,
        winDirection = 10,
        windSpeed = 0.0,
        isDay = 0,
        iconUrl = "",
        weatherCode = 0
    ),
    Hourly(
        time = "16:00",
        sunriseSunset = "",
        humidity = 1,
        pressure = 0,
        temp = 12.0,
        uvi = 0.0,
        visibility = 100,
        winDirection = 10,
        windSpeed = 0.0,
        isDay = 0,
        iconUrl = "",
        weatherCode = 0
    ),
    Hourly(
        time = "17:00",
        sunriseSunset = "",
        humidity = 1,
        pressure = 0,
        temp = 15.0,
        uvi = 0.0,
        visibility = 100,
        winDirection = 10,
        windSpeed = 0.0,
        isDay = 0,
        iconUrl = "",
        weatherCode = 0
    ), Hourly(
        time = "18:00",
        sunriseSunset = "Sunset",
        humidity = 1,
        pressure = 0,
        temp = 15.0,
        uvi = 0.0,
        visibility = 100,
        winDirection = 10,
        windSpeed = 0.0,
        isDay = 0,
        iconUrl = "",
        weatherCode = 0
    ), Hourly(
        time = "19:00",
        sunriseSunset = "",
        humidity = 1,
        pressure = 0,
        temp = 16.0,
        uvi = 0.0,
        visibility = 100,
        winDirection = 10,
        windSpeed = 0.0,
        isDay = 0,
        iconUrl = "",
        weatherCode = 0
    ), Hourly(
        time = "20:00",
        sunriseSunset = "",
        humidity = 1,
        pressure = 0,
        temp = 15.0,
        uvi = 0.0,
        visibility = 100,
        winDirection = 10,
        windSpeed = 0.0,
        isDay = 0,
        iconUrl = "",
        weatherCode = 0
    ), Hourly(
        time = "21:00",
        sunriseSunset = "",
        humidity = 1,
        pressure = 0,
        temp = 14.0,
        uvi = 0.0,
        visibility = 100,
        winDirection = 10,
        windSpeed = 0.0,
        isDay = 0,
        iconUrl = "",
        weatherCode = 0
    ), Hourly(
        time = "22:00",
        sunriseSunset = "",
        humidity = 1,
        pressure = 0,
        temp = 12.0,
        uvi = 0.0,
        visibility = 100,
        winDirection = 10,
        windSpeed = 0.0,
        isDay = 0,
        iconUrl = "",
        weatherCode = 0
    ), Hourly(
        time = "23:00",
        sunriseSunset = "",
        humidity = 1,
        pressure = 0,
        temp = 10.0,
        uvi = 0.0,
        visibility = 100,
        winDirection = 10,
        windSpeed = 0.0,
        isDay = 0,
        iconUrl = "",
        weatherCode = 0
    )
)