package com.weather.feature.forecast.components.hourlydata

import com.weather.model.Daily


internal val DailyStaticData = listOf(
    Daily(
        0,
        0.0,
        "Tomorrow",
        0,
        0.0,
        0,
        0,
        0.0,
        0,
        0,
        0,
        0.0,
        0.0,
        0.0,
        0,
        "Cloudy",
        "",
        "",
        0,
        0.0,
        0.0
    ),
    Daily(
        0,
        0.0,
        "Friday",
        0,
        0.0,
        0,
        0,
        0.0,
        0,
        0,
        0,
        0.0,
        0.0,
        0.0,
        0,
        "Rain",
        "",
        "",
        0,
        0.0,
        0.0
    ),
    Daily(
        0,
        0.0,
        "Saturday",
        0,
        0.0,
        0,
        0,
        0.0,
        0,
        0,
        0,
        0.0,
        0.0,
        0.0,
        0,
        "Cloudy",
        "",
        "",
        0,
        0.0,
        0.0
    ),
    Daily(
        0,
        0.0,
        "Sunday",
        0,
        0.0,
        0,
        0,
        0.0,
        0,
        0,
        0,
        0.0,
        0.0,
        0.0,
        0,
        "Sunny",
        "",
        "",
        0,
        0.0,
        0.0
    )
)
val DailyPreviewStaticData = listOf(
    Daily(
        dayTemp = 283.0,
        nightTemp = 275.0,
        time = "Tomorrow",
        icon = "",
        main = "Clouds",
        clouds = 0,
        dew_point = 0.0,
        humidity = 0,
        moon_phase = 0.0,
        moonrise = 0,
        moonset = 0,
        pop = 0.0,
        pressure = 0,
        sunrise = 0,
        sunset = 0,
        uvi = 0.0,
        id = 0,
        description = "",
        wind_deg = 0,
        wind_gust = 0.0,
        wind_speed = 0.0,
    ),
    Daily(
        dayTemp = 280.0,
        nightTemp = 274.0,
        time = "Wed",
        icon = "",
        main = "Snow",
        clouds = 0,
        dew_point = 0.0,
        humidity = 0,
        moon_phase = 0.0,
        moonrise = 0,
        moonset = 0,
        pop = 0.0,
        pressure = 0,
        sunrise = 0,
        sunset = 0,
        uvi = 0.0,
        id = 0,
        description = "",
        wind_deg = 0,
        wind_gust = 0.0,
        wind_speed = 0.0
    ),
    Daily(
        dayTemp = 284.0,
        nightTemp = 276.0,
        time = "Thur",
        icon = "",
        main = "Clouds",
        clouds = 0,
        dew_point = 0.0,
        humidity = 0,
        moon_phase = 0.0,
        moonrise = 0,
        moonset = 0,
        pop = 0.0,
        pressure = 0,
        sunrise = 0,
        sunset = 0,
        uvi = 0.0,
        id = 0,
        description = "",
        wind_deg = 0,
        wind_gust = 0.0,
        wind_speed = 0.0
    ),
    Daily(
        dayTemp = 278.0,
        nightTemp = 270.0,
        time = "Friday",
        icon = "",
        main = "Rain",
        clouds = 0,
        dew_point = 0.0,
        humidity = 0,
        moon_phase = 0.0,
        moonrise = 0,
        moonset = 0,
        pop = 0.0,
        pressure = 0,
        sunrise = 0,
        sunset = 0,
        uvi = 0.0,
        id = 0,
        description = "",
        wind_deg = 0,
        wind_gust = 0.0,
        wind_speed = 0.0
    ),
    Daily(
        dayTemp = 281.0,
        nightTemp = 269.0,
        time = "Saturday",
        icon = "",
        main = "Snow",
        clouds = 0,
        dew_point = 0.0,
        humidity = 0,
        moon_phase = 0.0,
        moonrise = 0,
        moonset = 0,
        pop = 0.0,
        pressure = 0,
        sunrise = 0,
        sunset = 0,
        uvi = 0.0,
        id = 0,
        description = "",
        wind_deg = 0,
        wind_gust = 0.0,
        wind_speed = 0.0
    )
)